version: '3.8'
services:
  redis:
    image: redis:7.0.2-alpine
    restart: always
    ports:
      - 127.0.0.1:6379:6379
  worker:
    image: hibiken/asynqmon:0.7
    ports:
      - 127.0.0.1:8080:8080
    command: --redis-addr=redis:6379
